language: java

install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: swapsipersonalc
  default: true
  on:
    repo: Bookrage001/PersonalSwapsiDev
    all_branches: true
