sudo: false
language: java
services:
  - docker
cache:
  directories:
    - "$HOME/target"
install:
  - mvn install
script:
  - mvn test -B

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn package appengine:deploy"
  skip_cleanup: true
  on:
    tags: true
