language: java
sudo: false
install:
  - mvn install
script:
  - mvn test -B
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: swapsipersonalc
  default: true
  on:
    repo: Bookrage001/PersonalSwapsiDev
    all_branches: false

before_install:
  - openssl aes-256-cbc -K $encrypted_343c2800c808_key -iv $encrypted_343c2800c808_iv
    -in SwapsiPersonalC-08be635cfa2b.json.enc -out SwapsiPersonalC-08be635cfa2b.json
    -d
