sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/target"
notifications:
- caleb.ardern@gmail.com
install:
- mvn install
script:
- mvn test -B
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn package appengine:deploy
  skip_cleanup: true
  on:
    repo: Bookrage001/PersonalSwapsiDev
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_343c2800c808_key -iv $encrypted_343c2800c808_iv
  -in SwapsiPersonalC-08be635cfa2b.json.enc -out SwapsiPersonalC-08be635cfa2b.json
  -d
